### ISSUE TITLE
[BUG] Errors in Setting Up Perseus

### ISSUE THREAD

**Issue by TheCedarPrince** [OHDSI/Perseus#7]
Hi Perseus Team,

Saw your recent presentations about the Perseus project at various OHDSI calls - amazing work! Very excited about it and have already started exploring how to use it. With that said, I have run into a variety of errors with setting up Perseus and am blocked. Was hoping I could receive some assistance. The following sections break up what I have encountered.

## System and Software Details

Operating System: RHEL 8
Docker version: N/A
Podman: 4.1.1
Perseus: 6a40cd615cf63d08094fe748cb5de2655eb8fb52

> Merge: 86ee545a 72b7c426
> Author: Matvey Chudakov <40443101+chMatvey@users.noreply.github.com>
> Date:   Sat Sep 17 10:22:06 2022 +0300
> 
>     Merge pull request #675 from SoftwareCountry/staging
>     
>     Staging

## Attempted Procedure and Expected Result

1. Clone Perseus repo onto computer: 
	- `git clone git@github.com:OHDSI/Perseus.git`
2. Make sure to have `podman` and `podman-compose` installed on your machine
	- For RHEL based systems `sudo dnf install podman podman-compose`
	- For Debian based systems `sudo apt-get install podman podman-compose`
	- For OSX systems `sudo brew install podman podman-compose`
3. Navigate to `https://athena.ohdsi.org/vocabulary/list` and download all vocabularies that do not require a license 
	- This will take 15 - 20 minutes
4. With the downloaded Athena zip, save it to the `perseus/vocabulary-db` directory.
5. Create a new folder within `vocabulary-db` called `vocabulary`
6. Unzip the Athena zip file into `vocabulary`
7. Navigate to the root of the Perseus repository and run the shell script `startup.sh` 
	- Could be run `bash startup.sh` or `./startup.sh`
8. Navigate one level up from the root of the Perseus repository and clone the following repository:
	- `git clone https://github.com/SoftwareCountry/ETL-CDMBuilder.git`
9. Edit the Dockerfile and change where it says: `build: ../ETL-CDMBuilder` to `build: ../ETL-CDMBuilder/source` 
10. Start the compose process by running: `sudo podman-compose up -d`

I expect that the compose process should just "work" and can navigate to `https://localhost:80` from my browser.

> NOTE: Step 8 and 9 were required as the OHDSI ETL-CDMBuilder that Perseus tries to call is too old and errors. I noticed that the SoftwareCountry fork had the most recent changes and so replaced that step within the Docker process manually to provide a recent version that had an existing Dockerfile - the other version does not have a Dockerfile and errors. 

## What Actually Happens

Instead, of the above process working, the process fails and I am unable to access Perseus. Here is the error message that I see after everything builds:

```
STEP 1/33: FROM r-base:4.1.3
STEP 2/33: ARG prop=default
--> Using cache f50afaf4061e1e70d6eaa1cbb3f66647737ae4f67aa92c027926e8252f11e1b6
--> f50afaf4061
STEP 3/33: RUN apt-get update
Get:1 http://deb.debian.org/debian testing InRelease [161 kB]
Get:2 http://deb.debian.org/debian testing/main amd64 Packages [8,490 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian sid InRelease [158 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian sid/main amd64 Packages [9,343 kB]
Fetched 18.2 MB in 3s (6,197 kB/s)
Reading package lists...['podman', '--version', '']
using podman version: 4.1.1
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_web']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_shareddb']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_frontend']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_vocabularydb']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_files-manager']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_user']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_solr']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_r-serve']
podman build -t perseus_r-serve -f ../DataQualityDashboard/R/Dockerfile --build-arg prop=docker ../DataQualityDashboard/R
exit code: 134
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_backend']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_white-rabbit']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_athena']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_cdm-builder']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_usagi']
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'perseus_data-quality-dashboard']
['podman', 'network', 'exists', 'perseus_default']
podman create --name=web --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=web --net perseus_default --network-alias web -p 80:80 --restart always perseus_web
exit code: 125
podman volume inspect perseus_shareddb || podman volume create perseus_shareddb
['podman', 'volume', 'inspect', 'perseus_shareddb']
['podman', 'network', 'exists', 'perseus_default']
podman create --name=shareddb --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=shareddb -v perseus_shareddb:/data/postgres --net perseus_default --network-alias shareddb -p 5432:5432 perseus_shareddb
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=frontend --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=frontend --net perseus_default --network-alias frontend -p 4200:4200 perseus_frontend
exit code: 125
podman volume inspect perseus_vocabularydb || podman volume create perseus_vocabularydb
['podman', 'volume', 'inspect', 'perseus_vocabularydb']
['podman', 'network', 'exists', 'perseus_default']
podman create --name=vocabularydb --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=vocabularydb -v perseus_vocabularydb:/data/postgres --net perseus_default --network-alias vocabularydb -p 5431:5432 --healthcheck-command /bin/sh -c pg_isready' '-q' '-d' 'vocabulary' '-U' 'perseus --healthcheck-interval 30s --healthcheck-timeout 60s --healthcheck-retries 10 perseus_vocabularydb
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=files-manager --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=files-manager -e SPRING_PROFILES_ACTIVE=docker --net perseus_default --network-alias files-manager -p 10500:10500 perseus_files-manager
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=user --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=user --env-file /home/jzelko3@icl.gtri.org/FOSS/Perseus/user/user-envs.txt -e USER_ENV=Docker --net perseus_default --network-alias user -p 5001:5001 perseus_user
exit code: 125
podman volume inspect perseus_solr || podman volume create perseus_solr
['podman', 'volume', 'inspect', 'perseus_solr']
['podman', 'network', 'exists', 'perseus_default']
podman create --name=solr --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=solr -v perseus_solr:/var/solr --net perseus_default --network-alias solr -p 8983:8983 perseus_solr
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=r-serve --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=r-serve --net perseus_default --network-alias r-serve -p 6311:6311 perseus_r-serve
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=backend --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=backend -e PERSEUS_ENV=Docker --net perseus_default --network-alias backend -p 5000:5000 perseus_backend
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=white-rabbit --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@icl.gtri.org/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=white-rabbit -e SPRING_PROFILES_ACTIVE=docker --net perseus_default --network-alias white-rabbit -p 8000:8000 perseus_white-rabbit
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
Starting OpenBSD Secure Shell server: sshd.

PostgreSQL Database directory appears to contain a database; Skipping initialization

Starting OpenBSD Secure Shell server: sshd.

PostgreSQL Database directory appears to contain a database; Skipping initialization

,--.   ,--. ,--.      ,--.   ,--.             ,------.           ,--.    ,--.    ,--.   ,--.
|  |   |  | |  ,---.  `--' ,-'  '-.  ,---.    |  .--. '  ,--,--. |  |-.  |  |-.  `--' ,-'  '-.
|  |.'.|  | |  .-.  | ,--. '-.  .-' | .-. :   |  '--'.' ' ,-.  | | .-. ' | .-. ' ,--. '-.  .-'
|   ,'.   | |  | |  | |  |   |  |   \   --.   |  |\  \  \ '-'  | | `-' | | `-' | |  |   |  |
'--'   '--' `--' `--' `--'   `--'    `----'   `--' '--'  `--`--'  `---'   `---'  `--'   `--'

WhiteRabbitService 0.4.0
Powered by Spring Boot 2.6.3
2022-09-29 20:08:03.576  INFO 1 --- [           main] c.a.w.WhiteRabbitServiceApplication      : Starting WhiteRabbitServiceApplication v0.4.0 using Java 17.0.2 on 46a72233bf0d with PID 1 (/app.jar started by root in /)
2022-09-29 20:08:03.578  INFO 1 --- [           main] c.a.w.WhiteRabbitServiceApplication      : The following profiles are active: docker
2022-09-29 20:08:04.538  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-09-29 20:08:04.723  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 176 ms. Found 9 JPA repository interfaces.
2022-09-29 20:08:05.539  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8000 (http)
2022-09-29 20:08:05.555  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-09-29 20:08:05.556  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-09-29 20:08:05.617  INFO 1 --- [           main] o.a.c.c.C.[.[localhost].[/white-rabbit]  : Initializing Spring embedded WebApplicationContext
2022-09-29 20:08:05.617  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1992 ms
2022-09-29 20:08:05.848  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-09-29 20:08:05.964  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.4.Final
2022-09-29 20:08:06.196  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-09-29 20:08:06.367  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-09-29 20:08:06.681  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-09-29 20:08:06.702  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
App config initialized
2022-09-29 20:08:08.389  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-09-29 20:08:08.400  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'

,------.              ,--.               ,-----.                      ,--. ,--.   ,--.               ,------.                    ,--.      ,--.                                ,--.
|  .-.  \   ,--,--. ,-'  '-.  ,--,--.   '  .-.  '   ,--.,--.  ,--,--. |  | `--' ,-'  '-. ,--. ,--.   |  .-.  \   ,--,--.  ,---.  |  ,---.  |  |-.   ,---.   ,--,--. ,--.--.  ,-|  |
|  |  \  : ' ,-.  | '-.  .-' ' ,-.  |   |  | |  |   |  ||  | ' ,-.  | |  | ,--. '-.  .-'  \  '  /    |  |  \  : ' ,-.  | (  .-'  |  .-.  | | .-. ' | .-. | ' ,-.  | |  .--' ' .-. |
|  '--'  / \ '-'  |   |  |   \ '-'  |   '  '-'  '-. '  ''  ' \ '-'  | |  | |  |   |  |     \   '     |  '--'  / \ '-'  | .-'  `) |  | |  | | `-' | ' '-' ' \ '-'  | |  |    \ `-' |
`-------'   `--`--'   `--'    `--`--'    `-----'--'  `----'   `--`--' `--' `--'   `--'   .-'  /      `-------'   `--`--' `----'  `--' `--'  `---'   `---'   `--`--' `--'     `---'
                                                                                         `---'
DataQualityDashboard 0.0.4
Powered by Spring Boot 2.6.3
2022-09-29 20:08:09.316  INFO 1 --- [           main] c.a.D.DataQualityDashboardApplication    : Starting DataQualityDashboardApplication v0.0.4 using Java 17-ea on 68e203986cb1 with PID 1 (/app.jar started by root in /)
2022-09-29 20:08:09.320  INFO 1 --- [           main] c.a.D.DataQualityDashboardApplication    : The following profiles are active: docker
2022-09-29 20:08:09.410  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-09-29 20:08:09.802  INFO 1 --- [           main] c.a.c.i.jackson.JacksonVersion           : Package versions: jackson-annotations=2.13.1, jackson-core=2.13.1, jackson-databind=2.13.1, jackson-dataformat-xml=2.13.1, jackson-datatype-jsr310=2.13.1, azure-core=1.26.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
2022-09-29 20:08:09.883  INFO 1 --- [           main] AbstractAzureServiceClientBuilderFactory : Will configure the default credential of type DefaultAzureCredential for class com.azure.identity.DefaultAzureCredentialBuilder.
2022-09-29 20:08:10.342  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8000 (http) with context path '/white-rabbit'
2022-09-29 20:08:10.359  INFO 1 --- [           main] c.a.w.WhiteRabbitServiceApplication      : Started WhiteRabbitServiceApplication in 7.337 seconds (JVM running for 7.835)
2022-09-29 20:08:10.574  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-09-29 20:08:10.762  INFO 1 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 177 ms. Found 3 JPA repository interfaces.
2022-09-29 20:08:11.294  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8001 (http)
2022-09-29 20:08:11.305  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2022-09-29 20:08:11.305  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.56]
2022-09-29 20:08:11.347  INFO 1 --- [           main] o.a.c.c.C.[.[.[/data-quality-dashboard]  : Initializing Spring embedded WebApplicationContext
2022-09-29 20:08:11.347  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1946 ms
2022-09-29 20:08:11.532  INFO 1 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-09-29 20:08:11.585  INFO 1 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.4.Final
2022-09-29 20:08:11.772  INFO 1 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-09-29 20:08:11.896  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-09-29 20:08:12.100  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-09-29 20:08:12.119  INFO 1 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQLDialect
2022-09-29 20:08:12.906  INFO 1 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-09-29 20:08:12.916  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-09-29 20:08:13.423  WARN 1 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2022-09-29 20:08:13.617  INFO 1 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page: class path resource [static/index.html]
2022-09-29 20:08:13.747  INFO 1 --- [           main] c.a.c.i.jackson.JacksonVersion           : Package versions: jackson-annotations=2.13.1, jackson-core=2.13.1, jackson-databind=2.13.1, jackson-dataformat-xml=2.13.1, jackson-datatype-jsr310=2.13.1, azure-core=1.26.0, Troubleshooting version conflicts: https://aka.ms/azsdk/java/dependency/troubleshoot
2022-09-29 20:08:13.813  INFO 1 --- [           main] AbstractAzureServiceClientBuilderFactory : Will configure the default credential of type DefaultAzureCredential for class com.azure.identity.DefaultAzureCredentialBuilder.
2022-09-29 20:08:14.058  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8001 (http) with context path '/data-quality-dashboard'
2022-09-29 20:08:14.066  INFO 1 --- [           main] c.a.D.DataQualityDashboardApplication    : Started DataQualityDashboardApplication in 5.804 seconds (JVM running for 7.004)
2022-09-29 20:08:14.087  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-09-29 20:08:14.102 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:772) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:753) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar!/:2.6.3]
	at com.arcadia.DataQualityDashboard.DataQualityDashboardApplication.main(DataQualityDashboardApplication.java:17) ~[classes!/:0.0.4]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:0.0.4]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:0.0.4]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:0.0.4]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:0.0.4]
Caused by: com.arcadia.DataQualityDashboard.service.error.RException: Cannot connect: r-serve
	at com.arcadia.DataQualityDashboard.service.r.RConnectionCreatorImpl.createRConnection(RConnectionCreatorImpl.java:70) ~[classes!/:0.0.4]
	at com.arcadia.DataQualityDashboard.DataQualityDashboardApplication.lambda$run$0(DataQualityDashboardApplication.java:24) ~[classes!/:0.0.4]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:769) ~[spring-boot-2.6.3.jar!/:2.6.3]
	... 13 common frames omitted
Caused by: org.rosuda.REngine.Rserve.RserveException: Cannot connect: r-serve
	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:90) ~[Rserve-1.8.1.jar!/:na]
	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:60) ~[Rserve-1.8.1.jar!/:na]
	at com.arcadia.DataQualityDashboard.service.r.RConnectionCreatorImpl.createRConnection(RConnectionCreatorImpl.java:56) ~[classes!/:0.0.4]
	... 15 common frames omitted
Caused by: java.net.UnknownHostException: r-serve
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:331) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:630) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:581) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:505) ~[na:na]
	at java.base/java.net.Socket.<init>(Socket.java:285) ~[na:na]
	at org.rosuda.REngine.Rserve.RConnection.<init>(RConnection.java:85) ~[Rserve-1.8.1.jar!/:na]
	... 17 common frames omitted

2022-09-29 20:08:14.115  INFO 1 --- [           main] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-09-29 20:08:14.117  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-09-29 20:08:14.121  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
10.89.0.1 - - [29/Sep/2022:20:12:05 +0000] "GET / HTTP/1.1" 499 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.115 Safari/537.36" "-"
10.89.0.1 - - [29/Sep/2022:20:13:05 +0000] "GET / HTTP/1.1" 504 569 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.115 Safari/537.36" "-"
podman create --name=athena --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@[REDACTED]/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=athena -e ATHENA_ENV=Docker --net perseus_default --network-alias athena -p 5002:5002 perseus_athena
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=cdm-builder --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@[REDACTED]/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=cdm-builder -e ASPNETCORE_ENVIRONMENT=Docker --net perseus_default --network-alias cdm-builder -p 9000:9000 perseus_cdm-builder
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=usagi --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@[REDACTED]/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=usagi -e USAGI_ENV=Docker --net perseus_default --network-alias usagi -p 5003:5003 perseus_usagi python /app/main.py
exit code: 125
['podman', 'network', 'exists', 'perseus_default']
podman create --name=data-quality-dashboard --label io.podman.compose.config-hash=123 --label io.podman.compose.project=perseus --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=perseus --label com.docker.compose.project.working_dir=/home/jzelko3@[REDACTED]/FOSS/Perseus --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=data-quality-dashboard -e SPRING_PROFILES_ACTIVE=docker --net perseus_default --network-alias data-quality-dashboard -p 8001:8001 perseus_data-quality-dashboard
exit code: 125
podman start -a web
podman start -a shareddb
podman start -a frontend
podman start -a vocabularydb
podman start -a files-manager
podman start -a user
podman start -a solr
podman start -a r-serve
exit code: 125
podman start -a backend
podman start -a white-rabbit
podman start -a athena
podman start -a cdm-builder
podman start -a usagi
podman start -a data-quality-dashboard
exit code: 1
exit code: 139
2022-09-29 20:13:35.925  INFO 1 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-09-29 20:13:35.927  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-09-29 20:13:35.949  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

```

I am quite at a loss as to what to do -- I doubt that it is `podman` related as `podman` is a drop-in replacement for `docker`. It seems to me coming more from step in the build process as I do have `r-serve` seemingly fail to be built.

Happy to report more on this so we can figure out what to do! Thanks for all the hard work so far!

~ tcp :deciduous_tree: 

## Misc Notes

> NOTE: There will be some interactive prompts that pop-up you will need to navigate through in the compose process
> NOTE: This will take a tremendous amount of time to set-up so don't be concerned if this is so slow
> NOTE: For some reason, one cannot be connected to any VPN while running this stack or else there will be download errors.

**Comment by chMatvey** [comment]
Hi @TheCedarPrince,

Thank you for your feedback! Sorry for the problems that you encountered during the deployment.
Can you please make theese steps:
1. Pull last commits in all repos;
2. Build r-serve independently: 
`cd DataQualityDashboard/R`
`<docker | podman> build -t r-serve --build-arg prop='docker' .`;
3. If it completed successfully, please try build all containers via compose, if not send error message.

About your 9 step (edit Dockerfile in ETL-CDMBuilder), it fixed in last commits.

**Comment by TheCedarPrince** [comment]
Hi @chMatvey ! 

Thank you for the response! This was indeed helpful!

I followed your steps but unfortunately, for some unknown reason, the issue still persists. However, I was able to get Perseus set up although I had to make some significant changes. As follows is the breakdown for my process:

## Attempted Procedure and Expected Result

**NOTE: The relevant new steps start at step 7**

1. Clone Perseus repo onto computer: 
	- `git clone git@github.com:OHDSI/Perseus.git`
2. Make sure to have `podman` and `podman-compose` installed on your machine
3. Navigate to `https://athena.ohdsi.org/vocabulary/list` and download all vocabularies that do not require a license 
	- This will take 15 - 20 minutes
4. With the downloaded Athena zip, save it to the `perseus/vocabulary-db` directory.
5. Create a new folder within `vocabulary-db` called `vocabulary`
6. Unzip the Athena zip file into `vocabulary`
7. Navigate one level up from the root of the Perseus repository and clone the following repository:
	- `git clone https://github.com/SoftwareCountry/ETL-CDMBuilder.git`
	- `git clone https://github.com/SoftwareCountry/DataQualityDashboard.git`
 	- `git clone https://github.com/SoftwareCountry/WhiteRabbit.git`
 8. Within the DataQualityDashboard, navigate to the `R` directory
 9. Replace the present Dockerfile with the following Dockerfile:
 
```Dockerfile
FROM almalinux:9

ARG prop=default

RUN dnf -y install libgcrypt-devel
RUN dnf -y install openssl-devel
RUN dnf -y install openssh-server
RUN dnf -y install epel-release
RUN dnf -y update && dnf -y install dnf-plugins-core && dnf -y config-manager --enable epel
RUN dnf -y install yum-utils && dnf -y update && dnf -y config-manager --set-enabled crb
RUN dnf -y install R
RUN dnf -y install java-11-openjdk

RUN export ROOTPASS=$(head -c 12 /dev/urandom |base64 -) && echo "root:$ROOTPASS" | chpasswd

COPY sshd_config /etc/ssh/

RUN R -e "r = getOption('repos'); r['CRAN'] = 'http://cran.us.r-project.org'; options(repos = r); install.packages('DatabaseConnector')"
RUN R -e "r = getOption('repos'); r['CRAN'] = 'http://cran.us.r-project.org'; options(repos = r); install.packages('SqlRender')"
RUN R -e "r = getOption('repos'); r['CRAN'] = 'http://cran.us.r-project.org'; options(repos = r); install.packages('ParallelLogger')"
RUN R -e "r = getOption('repos'); r['CRAN'] = 'http://cran.us.r-project.org'; options(repos = r); install.packages('devtools')"
RUN R -e "remotes::install_github('OHDSI/DataQualityDashboard')"
RUN R -e "install.packages('Rserve',, 'http://rforge.net/', type='source')"

VOLUME /rserve

WORKDIR .

COPY execution.R root/R/execution.R
COPY dqd-database-manager.R root/R/dqd-database-manager.R
COPY data-quality-check.R root/R/data-quality-check.R
COPY download-jdbc-drivers.R root/R/download-jdbc-drivers.R
COPY log-appender.R root/R/log-appender.R
COPY test-connection.R root/R/test-connection.R

# Enable tls 1.0, 1.1
COPY java-secure java-secure
RUN tr -d '\015' <./java-secure >./java-secure.tmp && mv ./java-secure.tmp ./java-secure && chmod 700 ./java-secure
RUN ./java-secure

COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

EXPOSE 6311 2222

CMD ["./entrypoint.sh"]
```

10. Edit the `java-secure` file to the following:

```bash
search="jdk.tls.disabledAlgorithms=SSLv3, TLSv1, TLSv1.1, RC4, DES, MD5withRSA,"

replace="jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA,"

cd /usr/lib/jvm/jre-11-openjdk/conf/security/
sed -i "s/$search/$replace/" java.security
```

11. Run the following build command: `sudo podman build -t r-serve --build-arg prop='docker' .`
12. Navigate to the Perseus directory and execute `sudo podman-compose up`

All images build correctly and follow the `docker-compose.yml` script so I expect that the compose process should just "work" and can navigate to `https://localhost:80` from my browser. This failed to start initially but then when I restarted all podman images/containers that were running and re-ran compose, this worked.

> NOTE: Step 9 was needed as there was a strange error I identified with RHEL-based systems on the current R-Base docker image you were using. I think the issue came less from RHEL and more from FIPS mode compliance we follow. The image kept consistently failing. Thus, I switched the base image and adjusted the Dockerfile.

> NOTE: Step 10 was needed to accommodate the new dockerfile but it should also be noted that hardcoding the path, as an aside, is probably not optimal unless it is absolutely required. 

@ssamus @chMatvey @paulnagy, happy to open a PR to add in notes to documentation, etc.. Otherwise, feel free to close this issue. :smile:

**Comment by ssamus** [comment]
@TheCedarPrince thank you for your feedback. @chMatvey  please review the TheCedarPrince's feedback and do any changes if needed

**Comment by natb1** [comment]
Hello, could you please clarify, it sounds like to get this to work we should be using the SoftwareCounty forks from the startup.sh, but also we should be manually switching to a particular commit in those dependency repos? Ex., [master of the data quality dashboard has no Dockerfile](https://github.com/SoftwareCountry/DataQualityDashboard/tree/master/R). Is there a combination of branches that are currently working?

**Comment by kostiushenko** [comment]
Hello, all actual code merged into master.
